# コピペでOK, app_nameもそのままでOK
# 19.01.20現在最新安定版のイメージを取得
FROM ruby:2.6.3

# 必要なパッケージのインストール（基本的に必要になってくるものだと思うので削らないこと）
RUN apt-get update -qq && \
  apt-get install -y build-essential \ 
  libpq-dev \        
  nodejs           

# 作業ディレクトリの作成、設定
RUN mkdir /heroku_test_app 
##作業ディレクトリ名をAPP_ROOTに割り当てて、以下$APP_ROOTで参照
ENV APP_ROOT /heroku_test_app  
WORKDIR $APP_ROOT

# ホスト側（ローカル）のGemfileを追加する（ローカルのGemfileは【３】で作成）
ADD ./heroku_test_app/Gemfile $APP_ROOT/Gemfile
ADD ./heroku_test_app/Gemfile.lock $APP_ROOT/Gemfile.lock

# Gemfileのbundle install
RUN gem install bundler:2.1.4
RUN bundle install
#ADD ./contacts_app $APP_ROOT
#ADD ./docker/web/database.yml $APP_ROOT/config/database.yml
